# -*- coding: utf-8 -*-
"""nlp-getting-started.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WfDhYQbe4dR0hcDnCSIxM5mpZKVcDtF
"""

import numpy as np
import pandas as pd
from sklearn import feature_extraction, linear_model, model_selection, preprocessing

from google.colab import files
files.upload()

import os
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c nlp-getting-started
!unzip nlp-getting-started.zip -d nlp

train_df = pd.read_csv('nlp/train.csv')
test_df = pd.read_csv('nlp/test.csv')

count_vectorizer = feature_extraction.text.CountVectorizer()

train_vectors = count_vectorizer.fit_transform(train_df["text"])
test_vectors = count_vectorizer.transform(test_df["text"])

clf = linear_model.RidgeClassifier()
scores = model_selection.cross_val_score(clf, train_vectors, train_df["target"], cv=3, scoring="f1")
clf.fit(train_vectors, train_df["target"])

sample_submission = pd.read_csv("nlp/sample_submission.csv")
sample_submission["target"] = clf.predict(test_vectors)
sample_submission.head()
sample_submission.to_csv("submission.csv", index=False)

files.download('submission.csv')